FRONTENDSCHOOL10/Code12hour

src/assets/icons/input/isChecked=false.svg, src/assets/icons/input/isChecked=true.svg, src/assets/icons/input/isSelected=false.svg, src/assets/icons/input/isSelected=true.svg, src/pages/login/index.html, src/pages/login/login.js, src/pages/login/login.scss, src/pages/register/index.html, src/pages/register/register.js, src/pages/register/register.scss
- 로그인, 회원가입 페이지 마크업
- 로그인, 회원가입 페이지 스타일링
- 회원가입 페이지 이메일 인증번호 input placeholder 수정
- 로그인,회원가입 페이지 헤더 풋터 연결완료
- 에셋 아이콘 체크박스, 라디오 svg 파일 추가
<br />
- 추천인 input 태그 만들기 
- 상품 리스트 컴포넌트 카테고리 만들기
<br />
resolves #3
=> feature : 로그인, 회원가입 페이지 마크업

index.html
- title 이름 변경
- 메인 페이지 <h> 태그 수정
- 미사용 클래스 제거
<br />
- 상품 목록 페이지 마크업
- 최근 본 상품 마크업
- 메인 페이지 팝업창
<br />
resolves #19
=> refactor: 메인 페이지 콘텐츠 구조 개선 및 미사용 클래스 제거

src/components/footer/footer.js, src/components/header/header.js, src/components/header/header.scss, vite.config.js
- 빌드 목록에 각 페이지 추가
- 헤더 컴포넌트 이미지 경로 일괄 수정
resolves #23
=> Chore: vite build 환경 수정

src/components/recent-product/index.html, src/components/recent-product/recent-product.js, src/components/recent-product/recent-product.scss
- 최근 본 상품 컴포넌트 마크업
<br />
- 최근 본 상품 컴포넌트 스타일링 수정
<br />
resolves #18
=> feat: 최근 본 상품 컴포넌트 마크업

src/pages/product-inquiry/index.html, src/pages/product-inquiry/product-inquiry.js, src/pages/product-inquiry/product-inquiry.scss
- 상품 문의 마크업 설계
<br />
- 설계 완료
- 웹접근성 고려
- scss 디자인
<br />
resolves #9
=> feat(issue 9): 상품 문의 마크업 설계

src/components/modal/index.html, src/components/modal/modal.scss, src/pages/product-inquiry/index.html, src/pages/product-inquiry/product-inquiry.scss, src/pages/product-review/index.html, src/pages/product-review/product-review.scss
- 스크린 리더 지원 강화를 위한 ARIA 속성 추가
- JavaScript 기능 구현을 위한 필요 속성 추가
- 접근성 향상을 위한 포커스 스타일 추가
- 특이성 최적화 및 코드 중복 감소
<br />
- 기능 구현
<br />
resolves #40
=> refactor: 유지보수 및 기능구현을 위한 마크업, 스타일링 리팩토링

src/components/modal/index.html, src/components/modal/modal.scss, src/pages/product-review/index.html, src/pages/product-review/product-review.js, src/pages/product-review/product-review.scss
- 후기 작성 모달창 (열기/닫기)
- textarea 포커스 시 내부 텍스트 삭제
- 입력 글자 수 카운터
- 내용 입력 시 등록 버튼 활성화
- 후기 작성 시 내용 입력 및 작성 날짜 반영
- 리뷰 유무에 따른 디스플레이
- 리뷰 개수 업데이트 기능
<br />
- 추천순, 등록순 필터링 
- 상품 문의 기능 구현
- (부가기능) 300자 이상 후기 베스트 아이콘
- (부가기능) 도움돼요 카운트
- (부가기능)
<br />
resolves #42
=> feature: 상품 후기 기능 구현

index.html, src/components/cart-button/cart-button.js, src/components/cart-button/cart-button.scss, src/components/cart-button/index.html, src/components/index.js, src/main.js
- 장바구니 버튼 마크업 및 스타일링
- 장바구니 버튼 클릭 시 모달창 띄우기
- 컴포넌트로 분리
<br />
- CSS 컨벤션 맞추기
<br />
resolves #36
=> feat: 메인 페이지 장바구니 버튼 클릭 시 모달창 띄우기

src/pages/product-inquiry/index.html, src/pages/product-inquiry/product-inquiry.js
- 문의하기 작성 가능 (모달창 열기 / 닫기)
- textarea 포커스 시 내부 텍스트 삭제
- 입력 글자 수 카운터
- 제목, 내용 입력 시 등록 버튼 활성화
- 후기 작성 시 내용 입력 및 작성 날짜 반영
<br />
<br />
resolves #49
=> feature: 상품 문의 기능 구현

src/components/modal/modal.js, src/components/modal/modal.scss
모달로 인한 화면 가림 버그 Fix
<br />
<br />
resolves #58
=> bugfix: 모달로 인한 화면 가림 버그 Fix

public/assets/icons/product-cart/DefaultMinus.svg, public/assets/icons/product-cart/Delete.svg, public/assets/icons/product-cart/Minus.svg, public/assets/icons/product-cart/Plus.svg, src/components/cart-button/cart-button.js, src/components/cart-button/cart-button.scss, src/pages/product-cart/index.html, src/pages/product-cart/product-cart.js, src/pages/product-cart/product-cart.scss, src/pages/product-detail/index.html
- 로컬 스토리지에 저장 되어있는 장바구니 상품들을 서버에 요청하여 데이터 렌더링 완료
- 장바구니 선택, 수량증가, 수량에 따른 합계 등 기능 구현 완료
- 장바구니 페이지 아이콘 에셋 추가
- 장바구니 담기 완료 후 모달 UI 수정
<br />
<br />
resolves #62
=> feature: 장바구니 페이지 기능 구현 및 데이터 통신

src/components/modal/modal.js, src/pages/login/index.html, src/pages/login/login.js, src/pages/login/login.scss
- 로그인 성공시 로컬스토리지에 auth라는 키값안 value에 유저 정보와 인증정보, 토큰 추가
- 로그인 실패시의 오류들 검증
- alert창 대신 modal 사용
<br />
<br />
resolves #67
=> feature: 로그인 페이지 기능 구현

src/components/product-inquiry/index.html, src/components/product-inquiry/product-inquiry.js, src/components/product-inquiry/product-inquiry.scss, src/components/product-review/index.html, src/components/product-review/product-review.js, src/components/product-review/product-review.scss
- 후기/문의 데이터 통신 구현 (후기 10개/페이지, 문의 5개/페이지)
- 페이지네이션 기능 추가
- 후기 필터링 기능 추가 (추천순, 등록순)
- 문의 비밀글 체크 기능 및 팝업창 구현
- 비밀글 데이터 통신
- 모달 활성화 시 백그라운드 스크롤 방지 기능 구현
<br />
- 추가 기능
- 버그 픽스
<br />
resolves #54
=> feat: 상품 후기 및 문의 기능 구현

src/api/defaultAuthData.js, src/api/index.js, src/components/cart-button/cart-button.js, src/components/header-small/header-small.js, src/components/header-small/header-small.scss, src/components/header/header.js, src/components/header/header.scss, src/pages/login/index.html, src/pages/login/login.js
- 로그인시 사용자명, 로그아웃 링크 렌더링 미로그인시 회원가입, 로그인 링크 렌더링
- 로그인시 배송지 등록이 아닌 변경을 할 수있도록 구현 (배송지 변경 로직은 아직 미완성)
- 미로그인시 배송지 등록을 권하고 로그인 버튼을 통해 로그인 가능
- header-small 타입 컴포넌트도 위와 같이 수정
- 로그아웃 기능 구현
<br />
- 배송지 변경 로직 구현
<br />
resolves #69
=> feature: 헤더 로그인에 따른 조건부 렌더링

public/assets/icons/arrow/category.svg, src/components/index.js, src/components/side-filter-panel/side-filter-panel.js, src/pages/product-list/index.html, src/pages/product-list/product-list.js, src/pages/product-list/product-list.scss
- pocketbase에서 데이터 받아와 상품 목록 렌더링
- 페이지네이션 기능
- 상단 필터링 기능 (신상품순, 판매량순, 혜택순, 낮은 가격순, 높은 가격순)
<br />
- 코드 리팩토링
<br />
resolves #46
=> feat: 상품 목록 렌더링

src/pages/register/add-options.js, src/pages/register/address-search.js, src/pages/register/agreement-checkboxes.js, src/pages/register/email-validation.js, src/pages/register/index.html, src/pages/register/invite-validation.js, src/pages/register/name-validation.js, src/pages/register/password-validation.js, src/pages/register/register.js, src/pages/register/register.scss, src/pages/register/submit-button.js, src/pages/register/username-validation.js, src/pages/register/utils.js
- api를 활용해 이메일 인증 기능 추가
<br />
- 데이터 추가하기
<br />
resolves #65
=> feat: 회원가입 페이지 기능 구현 및 데이터 통신

src/components/product-inquiry/index.html, src/components/product-inquiry/product-inquiry.js, src/components/product-review/index.html, src/components/product-review/product-review.js, src/components/product-review/product-review.scss, src/components/review-modal/modal.scss
- 로그인 사용자의 후기 및 문의 등록 기능
- 개인정보 보호 사용자 이름 마스킹 처리
- 비밀글 팝업창 오류 수정
- (c-modal) 로그인 알림창
- 입력창 테두리 디자인 제거
- 모달창에 현재 페이지 제품 정보 연동
- 로그인 관련 버그 수정:
- 로그인 알림창과 후기 작성창 중복 표시 해결
- 로그인 후 불필요한 알림창 표시 제거
- 문의 비밀글 작성자 열람 가능
<br />
- 리팩토링 필요
<br />
resolves #70
=> feature: 로그인 관련 문의, 후기 관련 기능 수정

src/components/product-inquiry/product-inquiry.js
- 문의 폼 버튼 비활성화 상태 이슈 해결
<br />
<br />
resolves #78
=> BigFix: 문의 입력 버튼 비활성화 이슈 해결

src/pages/product-cart/product-cart.js
- 장바구니 페이지 미로그인시 목록 보이지 않던 현상 수정
<br />
<br />
resolves #81
=> bugfix: 장바구니 페이지 미로그인시 목록 보이지 않던 현상 수정

src/components/product-inquiry/product-inquiry.js
- 비밀글 관련 버그 수정
<br />
<br />
resolves #80
=> BugFix: 비밀글 관련 버그 수정

src/components/product-review/product-review.js, src/components/product-review/product-review.scss
- 상품 문의 좋아요 자신에게는 좋아요를 누를 수 없습니다.
- 상품 문의 좋아요 타인의 후기에 1회만 누를 수 있습니다.
- 상품 문의 좋아요 로그인 후 기능을 사용 할 수 있습니다.
- 상품 문으 좋아요 버튼에 대한 접근성을 매우 잘지켰습니다.
- 후기 작성은 해당 상품당 1회 작성만 가능 하도록 변경 하였습니다.
<br />
<br />
resolves #85
=> feature: 상품 문의 좋아요 버튼 구현 및 후기 작성 로직 수정

README.md
- README.md 작성
<br />
resolves #90
=> Docs: README.md 재수정

src/components/cart-button/cart-button.js, src/components/header-small/header-small.js, src/components/header/header.js, src/pages/product-list/product-list.js, src/pages/register/address-search.js, src/pages/register/email-validation.js, src/pages/register/index.html, src/pages/register/invite-validation.js, src/pages/register/register.js, src/pages/register/register.scss, src/pages/register/submit-button.js, src/pages/register/username-validation.js, vite.config.js
- 검색어 입력시 엔터도 가능하게 수정
- 장바구니 담기 후 모달창 알림 뜰시 레이아웃 깨지는 현상 수정
- 회원가입 기본 alert창 modal창으로 변경
- 검색 필터 기준에 브랜드도 추가
- 회원가입 페이지 header small타입 연결
<br />
<br />
resolves #93
=> feature: 각 페이지 점검 및 수정

README.md
- README.md 파일 수정
<br />
<br />
resolves #97
=> docs: README.md 파일 수정

README.md, src/components/side-filter-panel/side-filter-panel.js, src/main.js, src/pages/product-list/product-list.js
- refactor: 스와이퍼 슬라이드가 변경될 때마다 alt 속성 업데이트
- docs: README 파일 폰트 컬러 변경
- refactor: Kulry → Karly로 텍스트 변경
<br />
- 모두 고생 많으셨습니다!!! 12조 최고~~
<br />
resolves #99
=> modify: 스와이퍼 슬라이드가 변경될 때마다 alt 속성 업데이트
